defaults:
  delay: 3
  priority_recheck: 6d-8d
  recheck: 60d-90d

hosts:
  # for module hosting facilities (rubygems, pypi, cpan) we set larger recheck time
  # since there are a lot of links, but the links are unlikely to change status
  cpan.metacpan.org: { priority_recheck: 14d-21d }
  dev.exherbo.org: { delay: 1 }
  dev.gentoo.org: { delay: 1 }
  files.pythonhosted.org: { delay: 1, priority_recheck: 14d-21d }
  github.com: { delay: 1, recheck: 21d-30d }
  github.io: { delay: 1, aggregate: true }
  gitlab.com: { delay: 1 }
  notabug.org: { delay: 60 }
  npmjs.com: { delay: 10 }
  npmjs.org: { delay: 10 }
  pypi.org: { delay: 1, priority_recheck: 14d-21d }
  rubygems.org: { delay: 1, priority_recheck: 14d-21d }
  search.cpan.org: { priority_recheck: 14d-21d }
  sf.net: { aggregate: true }
  sourceforge.net: { aggregate: true }
  buildd.debian.org: { delay: 60, recheck: 300d-360d } # sensitive to load
  crates.io: { skip: true } # misconfigured crap, always 404; XXX: this is true only for crate pages, not for e.g. https://crates.io/api/v1/crates/abscissa_core/0.5.2/download
  svnweb.freebsd.org: { skip: true } # misconfigured crap, always 403
  #src.fedoraproject.org: { recheck: 30d-60d } # very big
  #sting.dragonflybsd.org: { recheck: 21d-28d } # ipv6 always times out; XXX: need a way to disable IPv6 or lower the timeout for it, see #31 #32

  #
  # blacklist
  #

  # redirects to https://www.bestsevenreviews.com/best-linux-distros/ garbage
  mepis.org: { blacklist: true }

  # overtaken over by some iPhone Photography Equipment crap
  qtoctave.wordpress.com: { blacklist: true }

  # domain for sale
  nimuh.com: { blacklist: true }

  # overtaken by some game
  astroid.org: { blacklist: true }

  # overtaken by some french vpn "securify" garbage
  dejavu-fonts.org: { blacklist: true }

  # overtaken by some japanese company
  opentnl.org: { blacklist: true }

  # overtaken by some japanese health company
  ofset.org: { blacklist: true }

  # overtaken
  aseman.co: { blacklist: true }
  boutell.co.uk: { blacklist: true }
  conduit-project.org: { blacklist: true }
  coolreader.org: { blacklist: true }
  cross-pcg.com: { blacklist: true }
  ekg2.org: { blacklist: true }
  ferite.org: { blacklist: true }
  gnugadu.org: { blacklist: true }
  htdig.org: { blacklist: true }
  htpc-forum.de: { blacklist: true }
  jnickelsen.de: { blacklist: true }
  junoplay.com: { blacklist: true }
  kermit-project.org: { blacklist: true }
  kmldonkey.org: { blacklist: true }
  konst.org.ua: { blacklist: true }
  libcapn.org: { blacklist: true }
  mandriva.com: { blacklist: true }
  opensync.org: { blacklist: true }
  somethingaboutorange.com: { blacklist: true }
  svn.mandriva.com: { blacklist: true }
  thekonst.net: { blacklist: true }
  tkzinc.org: { blacklist: true }
  topfx.com: { blacklist: true }
  wmii.de: { blacklist: true }
  yafray.org: { blacklist: true }
